### ISSUE TITLE
Specify and implement transferable streams

### ISSUE THREAD

**Issue by guest271314** [WebAudio/web-audio-api-v2#78] opened 2020-05-15 13:40 UTC
**Describe the feature**
The comparision between using transferring a single stream (`ReadableStream`; `WritableStream`) and transferring hundreds of thousands of `TypedArray`s using `MessagePort.postMessage()` is not even close. 

`AudioWorklet` invariably outputs multiple gaps of silence at both Chromium and Firefox when thousands of messages are posted/`TypedArray`s transferred.

**Is there a prototype?**

Yes.

- https://docs.google.com/document/d/1_KuZzg5c3pncLJPFa8SuVm23AP4tft6mzPCL5at3I9M/edit
- https://bugs.chromium.org/p/chromium/issues/detail?id=894838

**Describe the feature in more detail**

See https://bugs.chromium.org/p/chromium/issues/detail?id=910471#c11.

Posting a single `ReadableStream`, e.g., from a `TransformStream` substantially reduces observable gaps in playback to 1 (that  bug is currently isolated to being observable at the end of reading/writing the stream,  not the underlying network request in the code used to get the stream) from multiple gaps randomly occurring during playback https://bugzilla.mozilla.org/show_bug.cgi?id=1629384#c24.

Compare for yourself https://plnkr.co/edit/nECtUZ (transferable streams implemented at Chromium behind `--enable-experimental-web-platform-features`); https://plnkr.co/edit/yh5A66UhMnlpq0JF (thousands of `postMessage(<TypedArray>, [<TypedArray.buffer>])` calls).

**Comment by padenot** [comment] 2020-06-16 14:44
Virtual F2F:
- Dupe of https://github.com/whatwg/streams/issues/276.

**Closed by padenot** 2020-06-16 14:44 UTC
Labels: feature

**Comment by guest271314** [comment] 2020-06-17 15:10
@padenot 

Perhaps the Virtual F2F participants did not understand the Issue. 

Am stating `MessagePort` does not work without gaps in audio output for substantial amount of input data.

Get rid of `MessagePort` altogether and substitute a `TransformStream` 

Main thread context (`WritableStream`) <= `TransformStream` => `AudioWorkletProcessor` (`AudioWorkletGlobalScope``) context (`ReadableStream`)
